### ISSUE TITLE
Need Python 3.6 

### ISSUE THREAD

**Issue by amalic** [dclong/docker-jupyterhub-toree#2]
I have seen you using Python 3.6 in your Docker stack. But the version on Dockerhub is still running Python 3.5.3.

Is there an easy way to upgrade it without the need to clone your whole stack?

**Comment by dclong** [comment]
@amalic The images on Dockerhub (based on this repostiory) hasn't been updated for a while as there are better alternatives. For your convenience, I've rebuilt images with Python 3.6. 

## Alterantives
https://hub.docker.com/r/dclong/jupyterhub-ds/

https://hub.docker.com/r/dclong/jupyterhub-scala/

Docker images based on either of the above repositories contains a Scala kernel. jupyterhub-ds is based on BeakerX and jupyterhub-scala is based on Almond. Neither of them has Spark preinstalled but you can get Spark as dependency just like how you'd develop a Spark application in Scala. You can check docs of BeakerX or Almond for getting dependent JARs.
